### ISSUE TITLE
Netlify Admin Interface 

### ISSUE THREAD

**Issue by dumbty** [stonecircle/ember-ghost-netlify-casper-template#1]
This is a great theme Kudos ! , but here is the thing i am unable to figure out  if I visit thistheme.netlify.com/admin it just says no page found . Is it not netlify cms ready ?

**Comment by mansona** [comment]
Hey @dumbty 👋 

I have updated the readme to explain the point of this repo, and hopefully that helps. 

Does that answer your question?

**Comment by dumbty** [comment]
@mansona 
Thank You sir ! You are really kind .
